### ISSUE TITLE
Add Yukon Software Sri Lanka

### ISSUE THREAD

**Issue by dakshinasd** [dilumn/peggedplacetowork#1]
Hi,
Please add Yukon Software Sri Lanka to this list. 
Company has pegged their salaries to Euro since September 2021.

Website: [http://yukon.lk](url)
LinkedIn: [https://www.linkedin.com/company/yukon-software-sri-lanka](url)

**Comment by dilumn** [comment]
Hi @dakshinasd thanks for the information. Added it
