### ISSUE TITLE
CAD - Pegged to currency

### ISSUE THREAD

**Issue by kelumt** [dilumn/peggedplacetowork#11]
We are from VitalHub Innovations Lab which is a Canadian based offshore product company. We are going to start Peg our salaries to Canadian Dollars (CAD), however currently there is no option to select the CAD in the request form. Can you please kindly attend and provide the option to select CAD?

**Comment by dilumn** [comment]
Hi @kelumt, CAD added https://github.com/dilumn/peggedplacetowork/pull/12
