### ISSUE TITLE
Fcode Labs should be in Great Place to Work list

### ISSUE THREAD

**Issue by Ramesh-X** [dilumn/peggedplacetowork#13]
Fcode Labs (https://www.fcodelabs.com) is pegging salaries to USD and also a Great Place to Work:tm:.

Listing on the website: https://greatplacetowork.lk/fcode-labs/

Thanks.

**Comment by dilumn** [comment]
Hi @Ramesh-X thanks for the information. I probably missed Fcode labs from the list. Added it now
