### ISSUE TITLE
Submit a new company update: SEBSA

### ISSUE THREAD

**Issue by Muthuraja83** [dilumn/peggedplacetowork#17]
Our company also salary adjusted with bucket of currencies. We are dealing with EUR, GBP and USD. We have created a weight with the revenue according to the growth of these currencies and giving as an allowance from April onwards to all employees.
Company: SEBSA (Pvt) Ltd [www.sebsaworld.com]

This is published in LinkedIn.

https://www.linkedin.com/feed/update/urn:li:activity:6919276552442572800

You can update this information.
Thank you

Best Regards
Muthuraja Nanayakkara

**Comment by dilumn** [comment]
Hi @Muthuraja83 Added SEBSA to the list https://peggedplacetowork.lk/?q%5Bname_cont%5D=SEBSA&q%5Bpegged_currency_eq%5D=&commit=Search
