### ISSUE TITLE
Add AtLink to the list

### ISSUE THREAD

**Issue by manjula-priyantha** [dilumn/peggedplacetowork#26]
Hi,

Pls add AtLink Communications Pvt Ltd into the list. Details as follows;

Company Name:  AtLink Communications
Web: https://atlinkcom.com

Pegged Currency: USD

Initial salary pegging value : 202 LKR
Salary proportion: Fully
Additional remarks: Effective from April 2022

Thanks!

BR,
Manjula

**Comment by dilumn** [comment]
Hi @manjula-priyantha, added to the list
