### ISSUE TITLE
Add Temenos Sri Lanka to company list

### ISSUE THREAD

**Issue by lasitharanaweera82** [dilumn/peggedplacetowork#47]
Add Temenos Sri Lanka to list

**Comment by dilumn** [comment]
Hi @lasitharanaweera82 can I know to which currency Temenos pegged? also if possible let me know
pegging value, fully or partially

**Comment by dilumn** [comment]
I added Temenos Sri Lanka as USD pegged company, let me know if it need to change

**Comment by lasitharanaweera82** [comment]
USD
