### ISSUE TITLE
Add VeroxLabs to the list

### ISSUE THREAD

**Issue by michelcanagasabey** [dilumn/peggedplacetowork#48]
Initial peg value 200.
Pegged to all employees from May

**Comment by michelcanagasabey** [comment]
pegged to the USD. Sorry missed it 
Entire salary is pegged

**Comment by michelcanagasabey** [comment]
pegged to the USD. Sorry missed it 
Entire salary is pegged

**Comment by michelcanagasabey** [comment]
pegged to the USD. Sorry missed it 
Entire salary is pegged

**Comment by dilumn** [comment]
@michelcanagasabey added VeroxLabs to the list
