### ISSUE TITLE
Missing Designation

### ISSUE THREAD

**Issue by dimuththarindu** [dilumn/peggedplacetowork#54]
Missing designation
01 - Support Engineer / Support Engineer I / Software Support Engineer / IT Support Executive
02 - Senior Support Engineer / Support Engineer II / Senior Software Support Engineer / Senior Software Engineer

**Comment by dilumn** [comment]
Hi @dimuththarindu sorry for the delay. Added `Support Engineer` & `Senior Support Engineer` designations
