### ISSUE TITLE
H2O.ai  - USD Pegged Salary 

### ISSUE THREAD

**Issue by ahsancse** [dilumn/peggedplacetowork#56]
Initial salary pegging value - 200.664 (1st of March USD to LKR Rate)
Salary proportion - Fully
Additional remarks - Paying full basic Salary pegged to USD since May as an Inflation allowance. 
EPF/ETF is calculated from basic salary. 
Interns allowance increased as well.

**Comment by dilumn** [comment]
Hi @ahsancse Thanks for the information. Added it
