### ISSUE TITLE
Please add Adelanka (Pvt) Ltd

### ISSUE THREAD

**Issue by Nalakaperera** [dilumn/peggedplacetowork#57]
Company - Adelanka (Pvt) Ltd
Pegged to currency - USD
Initial salary pegging value - 200 USD
Additional remarks - Paying salaries pegged to USD since April as an allowance.

**Comment by dilumn** [comment]
Hi @Nalakaperera added the information

**Comment by Nalakaperera** [comment]
Thanks Dilum!
