### ISSUE TITLE
Kognitiv Corporation

### ISSUE THREAD

**Issue by sampath-noetic** [dilumn/peggedplacetowork#59]
class NameOfDataMigration < ActiveRecord::Migration[7.0]
  def change
    Organization.create!(
      name: "Kognitiv Corporation",
      pegged: true,
      pegged_currency: 'GBP',
      remarks: 'Pegging started from April. Will be reviewed at the end of the year',
      pegging_value: 260::INT,
      proportion: fully
    )
  end
end

**Comment by dilumn** [comment]
@sampath-noetic sorry for late, I added this data

**Comment by sampath-noetic** [comment]
> @sampath-noetic sorry for late, I added this data

No Problems. Thank you..
