### ISSUE TITLE
Adding as a company which pay in Pegging 

### ISSUE THREAD

**Issue by MosiacHR** [dilumn/peggedplacetowork#61]
Hi Team, 
We pay our tech teams under pegging. Please add to the list. 

Best Regards, 
Gayan Nanayakkara
CEO|Director
MosiacHR Pvt Ltd.

**Comment by dilumn** [comment]
Hi @MosiacHR sorry for the late reply, can I know to which currency you are pegging? I will put as USD for now, but let me know if it is different

**Comment by MosiacHR** [comment]
Hi Diilum,
Yes USD for the time being.

Thank You & Best Regards,


GAYAN NANAYAKKARA
CEO
*MOSIAC H R Private** Limited*
P: +94117598376  M: *+94759991000*
A: Paramount Towers, Level 02, #192/10, Nawala, 10250, Sri Lanka | India |
Australia | Turkey
W: www.mosiachr.com <https://www.mosiachr.com/>E: ***@***.***
***@***.***>
[image: facebook] <https://www.facebook.com/MosiacHR>[image: twitter]
<https://twitter.com/Sheynu911>[image: Linked In]
<https://www.linkedin.com/company/mosiac-hr-private-limited>[image:
instagram] <https://www.instagram.com/mosiac_hr_private_limited/>
*P* *Save a tree. Do not print this **email** unless it is really
necessary. [* Consider the environment. Do you really need to print this
email? Before printing this e-mail message, ask yourself whether you really
need a hard copy.*]*
*Note:* This e-mail and any attachment hereto are confidential and is
intended only for the use of the addressee and may contain information that
is privileged or otherwise protected from disclosure. If you are not the
intended recipient, you are hereby notified that the use, review,
disclosure or copying of this e-mail and the information it contains is
prohibited. If you have received this message in error, please notify the
sender by reply e-mail and discard all of its contents by deleting this
message and the attachment, if any, from your system.

**Comment by dilumn** [comment]
Great I will keep it as USD
